/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fff8f5",
        "surface-dim": "#e1d8d4",
        "surface-bright": "#fff8f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fbf2ed",
        "surface-container": "#f5ece7",
        "surface-container-high": "#efe6e2",
        "surface-container-highest": "#e9e1dc",
        "on-surface": "#1e1b18",
        "on-surface-variant": "#584141",
        "inverse-surface": "#34302c",
        "inverse-on-surface": "#f8efea",
        "outline": "#8c7071",
        "outline-variant": "#e0bfbf",
        "surface-tint": "#af2b3e",
        "primary": "#570013",
        "on-primary": "#ffffff",
        "primary-container": "#800020",
        "on-primary-container": "#ff828a",
        "inverse-primary": "#ffb3b5",
        "secondary": "#775a19",
        "on-secondary": "#ffffff",
        "secondary-container": "#fed488",
        "on-secondary-container": "#785a1a",
        "tertiary": "#272725",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#3d3d3b",
        "on-tertiary-container": "#a9a8a4",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdada",
        "primary-fixed-dim": "#ffb3b5",
        "on-primary-fixed": "#40000b",
        "on-primary-fixed-variant": "#8e0f28",
        "secondary-fixed": "#ffdea5",
        "secondary-fixed-dim": "#e9c176",
        "on-secondary-fixed": "#261900",
        "on-secondary-fixed-variant": "#5d4201",
        "tertiary-fixed": "#e4e2de",
        "tertiary-fixed-dim": "#c8c6c3",
        "on-tertiary-fixed": "#1b1c1a",
        "on-tertiary-fixed-variant": "#474744",
        "background": "#fff8f5",
        "on-background": "#1e1b18",
        "surface-variant": "#e9e1dc"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "display-lg": ["'Playfair Display'", "serif"],
        "display-lg-mobile": ["'Playfair Display'", "serif"],
        "headline-md": ["'Playfair Display'", "serif"],
        "headline-sm": ["'Playfair Display'", "serif"],
        "body-lg": ["'Source Sans 3'", "sans-serif"],
        "body-md": ["'Source Sans 3'", "sans-serif"],
        "label-caps": ["'Source Sans 3'", "sans-serif"]
      },
      fontSize: {
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
